export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT: "LOGOUT",
};

export const adminConstants = {
  GET_ADMINS_REQUEST: "GET_ADMINS_REQUEST",
  GET_ADMINS_SUCCESS: "GET_ADMINS_SUCCESS",
  GET_ADMINS_FAILURE: "GET_ADMINS_FAILURE",

  GET_ADMIN_REQUEST: "GET_ADMIN_REQUEST",
  GET_ADMIN_SUCCESS: "GET_ADMIN_SUCCESS",
  GET_ADMIN_FAILURE: "GET_ADMIN_FAILURE",

  UPDATE_ADMIN_REQUEST: "UPDATE_ADMIN_REQUEST",
  UPDATE_ADMIN_SUCCESS: "UPDATE_ADMIN_SUCCESS",
  UPDATE_ADMIN_FAILURE: "UPDATE_ADMIN_FAILURE",
};

export const userConstants = {
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE",

  CREATE_USERS_SUCCESS: "CREATE_USERS_SUCCESS",
  CREATE_USERS_FAILURE: "CREATE_USERS_FAILURE",

  UPDATE_USERS_SUCCESS: "UPDATE_USERS_SUCCESS",
  UPDATE_USERS_FAILURE: "UPDATE_USERS_FAILURE",

  DELETE_USERS_SUCCESS: "DELETE_USERS_SUCCESS",

  EDIT_USERS_SUCCESS: "EDIT_USERS_SUCCESS",
};

export const wakamConstants = {
  GET_WAKAM_SERVICES_SUCCESS: "GET_WAKAM_SERVICES_SUCCESS",
  GET_WAKAM_SERVICES_FAILURE: "GET_WAKAM_SERVICES_FAILURE",
};

export const imaConstants = {
  GET_IMA_SERVICES_SUCCESS: "GET_IMA_SERVICES_SUCCESS",
  GET_IMA_SERVICES_FAILURE: "GET_IMA_SERVICES_FAILURE",
};

export const quotationConstants = {
  GET_QUOTATIONS_REQUEST: "GET_QUOTATIONS_REQUEST",
  GET_QUOTATIONS_SUCCESS: "GET_QUOTATIONS_SUCCESS",
  GET_QUOTATIONS_FAILURE: "GET_QUOTATIONS_FAILURE",

  GET_QUOTATION_REQUEST: "GET_QUOTATION_REQUEST",
  GET_QUOTATION_SUCCESS: "GET_QUOTATION_SUCCESS",
  GET_QUOTATION_FAILURE: "GET_QUOTATION_FAILURE",
};

export const imaQuotationConstants = {
  GET_QUOTATIONS_REQUEST: "GET_QUOTATIONS_REQUEST",
  GET_QUOTATIONS_SUCCESS: "GET_QUOTATIONS_SUCCESS",
  GET_QUOTATIONS_FAILURE: "GET_QUOTATIONS_FAILURE",

  GET_QUOTATION_REQUEST: "GET_QUOTATION_REQUEST",
  GET_QUOTATION_SUCCESS: "GET_QUOTATION_SUCCESS",
  GET_QUOTATION_FAILURE: "GET_QUOTATION_FAILURE",
};

export const popupConstants = {
  OPEN_POPUP: "OPEN_POPUP",
  CLOSE_POPUP: "CLOSE_POPUP",
};

export const headerConstants = {
  UPDATE_HEADER: "UPDATE_HEADER",
  ACTIVE_MENU: "ACTIVE_MENU"
};

export const userInfoConstants = {
  UPDATE_USER_INFO: "UPDATE_USER_INFO",
};

export const contractConstants = {
  GET_CONTRACTS_REQUEST: "GET_CONTRACTS_REQUEST",
  GET_CONTRACTS_SUCCESS: "GET_CONTRACTS_SUCCESS",
  GET_CONTRACTS_FAILURE: "GET_CONTRACTS_FAILURE",

  GET_CONTRACT_REQUEST: "GET_CONTRACT_REQUEST",
  GET_CONTRACT_SUCCESS: "GET_CONTRACT_SUCCESS",
  GET_CONTRACT_FAILURE: "GET_CONTRACT_FAILURE",
};

export const resiliationConstants = {
  GET_RESILATIONS_REQUEST: "GET_RESILATIONS_REQUEST",
  GET_RESILATIONS_SUCCESS: "GET_RESILATIONS_SUCCESS",
  GET_RESILATIONS_FAILURE: "GET_RESILATIONS_FAILURE",

  GET_RESILATION_REQUEST: "GET_RESILATION_REQUEST",
  GET_RESILATION_SUCCESS: "GET_RESILATION_SUCCESS",
  GET_RESILATION_FAILURE: "GET_RESILATION_FAILURE",
};

export const residentConstants = {
  GET_RESIDENTS_REQUEST: "GET_RESIDENTS_REQUEST",
  GET_RESIDENTS_SUCCESS: "GET_RESIDENTS_SUCCESS",
  GET_RESIDENTS_FAILURE: "GET_RESIDENTS_FAILURE",

  GET_RESIDENT_REQUEST: "GET_RESIDENT_REQUEST",
  GET_RESIDENT_SUCCESS: "GET_RESIDENT_SUCCESS",
  GET_RESIDENT_FAILURE: "GET_RESIDENT_FAILURE",
};

export const prospectConstants = {
  GET_PROSPECTS_REQUEST: "GET_PROSPECTS_REQUEST",
  GET_PROSPECTS_SUCCESS: "GET_PROSPECTS_SUCCESS",
  GET_PROSPECTS_FAILURE: "GET_PROSPECTS_FAILURE",

  GET_PROSPECT_REQUEST: "GET_PROSPECT_REQUEST",
  GET_PROSPECT_SUCCESS: "GET_PROSPECT_SUCCESS",
  GET_PROSPECT_FAILURE: "GET_PROSPECT_FAILURE",
};

export const imaUserConstants = {
  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE",

  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE",
};

export const interventionConstants = {
  GET_INTERVENTIONS_REQUEST: "GET_INTERVENTIONS_REQUEST",
  GET_INTERVENTIONS_SUCCESS: "GET_INTERVENTIONS_SUCCESS",
  GET_INTERVENTIONS_FAILURE: "GET_INTERVENTIONS_FAILURE",

  GET_INTERVENTION_REQUEST: "GET_INTERVENTION_REQUEST",
  GET_INTERVENTION_SUCCESS: "GET_INTERVENTION_SUCCESS",
  GET_INTERVENTION_FAILURE: "GET_INTERVENTION_FAILURE",
};
