export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT: 'LOGOUT',
};

export const adminConstants = {
    GET_ADMIN_REQUEST: 'GET_ADMIN_REQUEST',
    GET_ADMIN_SUCCESS: 'GET_ADMIN_SUCCESS',
    GET_ADMIN_FAILURE: 'GET_ADMIN_FAILURE',

    UPDATE_ADMIN_REQUEST: 'UPDATE_ADMIN_REQUEST',
    UPDATE_ADMIN_SUCCESS: 'UPDATE_ADMIN_SUCCESS',
    UPDATE_ADMIN_FAILURE: 'UPDATE_ADMIN_FAILURE',
};

export const userConstants = {
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',

    CREATE_USERS_SUCCESS: 'CREATE_USERS_SUCCESS',
    CREATE_USERS_FAILURE: 'CREATE_USERS_FAILURE',

    UPDATE_USERS_SUCCESS: 'UPDATE_USERS_SUCCESS',
    UPDATE_USERS_FAILURE: 'UPDATE_USERS_FAILURE',

    DELETE_USERS_SUCCESS: 'DELETE_USERS_SUCCESS',

    EDIT_USERS_SUCCESS: 'EDIT_USERS_SUCCESS',
};

export const wakamConstants = {
    GET_WAKAM_SERVICES_SUCCESS: 'GET_WAKAM_SERVICES_SUCCESS',
    GET_WAKAM_SERVICES_FAILURE: 'GET_WAKAM_SERVICES_FAILURE',
};

export const imaConstants = {
    GET_IMA_SERVICES_SUCCESS: 'GET_IMA_SERVICES_SUCCESS',
    GET_IMA_SERVICES_FAILURE: 'GET_IMA_SERVICES_FAILURE',
};

export const quotationConstants = {
    GET_QUOTATIONS_REQUEST: 'GET_QUOTATIONS_REQUEST',
    GET_QUOTATIONS_SUCCESS: 'GET_QUOTATIONS_SUCCESS',
    GET_QUOTATIONS_FAILURE: 'GET_QUOTATIONS_FAILURE',
};

export const contractConstants = {
    GET_CONTRACTS_REQUEST: 'GET_CONTRACTS_REQUEST',
    GET_CONTRACTS_SUCCESS: 'GET_CONTRACTS_SUCCESS',
    GET_CONTRACTS_FAILURE: 'GET_CONTRACTS_FAILURE',
};

export const resiliationConstants = {
    GET_RESILATION_REQUEST: 'GET_RESILATION_REQUEST',
    GET_RESILATION_SUCCESS: 'GET_RESILATION_SUCCESS',
    GET_RESILATION_FAILURE: 'GET_RESILATION_FAILURE',
};
